services:
  - type: web
    name: gemini-chatbot
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyAIiI3JVnnRTBRsJZbgw_QofBXtf1iWNZM
